import test from 'node:test';import assert from 'node:assert/strict';import {createRequestJournal} from './request-journal.mjs';
const value=i=>({action_key:'send_message',label:'Send',summary:'Metadata only',source_record_id:'',draft_record_id:'draft-'+i,run_id:'run-'+i,state:'succeeded',created_at:new Date(i*1000).toISOString()});
function fixture({states={},deny=[],casFail=[],wrongId=false}={}){const rows=new Map(Array.from({length:10},(_,i)=>['row-'+i,{record_id:'row-'+i,revision:3,value:{...value(i),state:states[i]||'succeeded'}}]));const reads=[],deleted=[],writes=[];const sdk={
async listPrivateState(){return {items:[...rows.values()].map(({value,...r})=>r)}},async readPrivateState(_,id){return {item:rows.get(id)}},
async request(operation,_,{run_id}){assert.equal(operation,'run_status');reads.push(run_id);if(deny.includes(run_id))throw Error('DENIED');return {id:wrongId?'foreign-run':run_id,state:states['current-'+run_id]||states[Number(run_id.slice(4))]||'succeeded'}},
async deletePrivateState(_,id,revision){assert.equal(revision,rows.get(id).revision);if(casFail.includes(id))throw Error('CAS');deleted.push(id);rows.delete(id)},
async putPrivateState(_,id,revision,v){assert.equal(revision,0);assert(!rows.has(id));writes.push(id);rows.set(id,{record_id:id,revision:1,value:v});return {item:{revision:1}}}};return {rows,reads,deleted,writes,journal:createRequestJournal(sdk,{uuid:()=> 'new-row'})};}
const entry={actionKey:'send_message',label:'Send',summary:'Next message',draftId:'new-draft'};
test('capacity reclaims only freshly verified oldest terminal metadata before reserving',async()=>{const f=fixture();await f.journal.load();await f.journal.reserve(entry);assert.deepEqual(f.deleted,['row-0']);assert.deepEqual(f.reads,['run-0']);assert.equal(f.rows.size,10);assert(f.rows.has('new-row'));});
test('fresh pending and unknown history stays while a verified terminal row can free capacity',async()=>{const f=fixture({states:{0:'unknown',1:'pending_approval',2:'pending'}});await f.journal.load();await f.journal.reserve(entry);assert.deepEqual(f.deleted,['row-3']);assert.deepEqual(f.reads,['run-0','run-1','run-2','run-3']);assert(f.rows.has('row-0')&&f.rows.has('row-1')&&f.rows.has('row-2'));});
test('all fresh pending or unknown rows keep cap closed without writes',async()=>{const f=fixture({states:Object.fromEntries(Array.from({length:10},(_,i)=>[i,i%2?'unknown':'pending']))});await f.journal.load();await assert.rejects(f.journal.reserve(entry),/REQUEST_JOURNAL_CAP/);assert.equal(f.reads.length,10);assert.deepEqual(f.deleted,[]);assert.deepEqual(f.writes,[]);});
test('denied or nonterminal status and CAS conflicts never delete that history',async()=>{const f=fixture({deny:['run-0'],states:{'current-run-1':'unknown_outcome'},casFail:['row-2']});await f.journal.load();await f.journal.reserve(entry);assert.deepEqual(f.deleted,['row-3']);assert(f.rows.has('row-0')&&f.rows.has('row-1')&&f.rows.has('row-2'));});
test('wrong Run identity never authorizes history deletion or new reservation',async()=>{const f=fixture({wrongId:true});await f.journal.load();await assert.rejects(f.journal.reserve(entry),/REQUEST_JOURNAL_CAP/);assert.equal(f.reads.length,10);assert.deepEqual(f.deleted,[]);assert.deepEqual(f.writes,[]);});
test('ten cached queued Runs that actually succeeded allow the next send reservation',async()=>{const states=Object.fromEntries(Array.from({length:10},(_,i)=>[i,'queued']));for(let i=0;i<10;i++)states['current-run-'+i]='succeeded';const f=fixture({states});await f.journal.load();await f.journal.reserve(entry);assert.deepEqual(f.deleted,['row-0']);assert.deepEqual(f.reads,['run-0']);assert.equal(f.rows.size,10);});
test('unknown entries without Run IDs remain pinned and cannot be discarded',async()=>{const f=fixture();for(const row of f.rows.values()){row.value.run_id='';row.value.state='unknown';}await f.journal.load();await assert.rejects(f.journal.reserve(entry),/REQUEST_JOURNAL_CAP/);assert.deepEqual(f.reads,[]);assert.deepEqual(f.deleted,[]);assert.deepEqual(f.writes,[]);});
