import assert from 'node:assert/strict';
import {test} from 'node:test';
import {MailPreEffectValidationError,settleMailRuntimeEffect} from './runtime-effect.mjs';
const claim={run_id:'00000000-0000-4000-8000-000000000001'};
function fixture(effect,result=async()=>{}){const results=[],rows=[];return {sdk:{start:async()=>({input:{to:'not-an-email'}}),result:async(c,value)=>{results.push(value);await result();}},claim,action:'send_message',journal:{latest:()=>({}),append:r=>rows.push(r)},effect,results,rows};}
test('deterministic validation before effect settles failed without pausing/retrying',async()=>{let effects=0;const f=fixture(async()=>{effects++;throw new MailPreEffectValidationError();});const settled=await settleMailRuntimeEffect(f);assert.equal(effects,1);assert.equal(settled.provider_succeeded,false);assert.deepEqual(f.results,[{status:'returned',provider_succeeded:false,output:{operation_id:`mail-${claim.run_id}`,transport_outcome:'not_attempted',sent_copy_outcome:'not_applicable'}}]);assert.equal(f.rows.length,0);});
test('possible SMTP effect and reservation conflicts never claim known failure or retry',async()=>{for(const code of ['EMAIL_SMTP_OUTCOME_UNCONFIRMED','TRANSPORT_OUTCOME_UNCERTAIN_NO_AUTOMATIC_RESEND','EXACT_MAIL_INPUT_INVALID']){let effects=0;const f=fixture(async()=>{effects++;throw Error(code);});await assert.rejects(settleMailRuntimeEffect(f));assert.equal(effects,1);assert.equal(f.results.length,0);assert.equal(f.rows.length,0);}});
test('lost failure settlement remains unconfirmed and never retries',async()=>{const f=fixture(async()=>{throw new MailPreEffectValidationError();},async()=>{throw Error('RESULT_LOST');});await assert.rejects(settleMailRuntimeEffect(f),/RESULT_LOST/);assert.equal(f.results.length,1);});
test('successful effect retains existing output and reported journal',async()=>{const output={operation_id:'mail-ok',transport_outcome:'smtp_accepted',sent_copy_outcome:'accepted'},f=fixture(async()=>output);assert.equal((await settleMailRuntimeEffect(f)).provider_succeeded,true);assert.equal(f.results[0].output,output);assert.equal(f.rows[0].state,'reported');});
