import assert from 'node:assert/strict';
import {withTransportIdentity,withReplyParent} from './transport-identity.mjs';
import {canonicalMail} from './sent-copy.mjs';
import {createMailProvider} from './mail.mjs';
import {createHash} from 'node:crypto';
const id='00000000-0000-4000-8000-000000000001',input={to:'recipient@example.test',subject:'Identity',body:'Exact approved text'};
const a=withTransportIdentity(id,'send_message',input),b=withTransportIdentity(id.toUpperCase(),'send_message',input);
assert.equal(a.message_id,b.message_id);assert(!Object.hasOwn(input,'message_id'));
assert.throws(()=>withTransportIdentity('untrusted','send_message',input),/EXACT_MAIL_RUN_INVALID/);
assert.throws(()=>withTransportIdentity(id,'send_message',{...input,message_id:'<supplied@test>'}),/SUPPLIED_TRANSPORT_ID_NOT_ALLOWED/);
const fixedDate=new Date('2026-09-28T00:00:00Z');
const first=await canonicalMail('owner@example.test','send_message',a,fixedDate),second=await canonicalMail('owner@example.test','send_message',b,fixedDate);
assert.equal(first.digest,second.digest);assert(first.bytes.includes(Buffer.from(a.message_id)));
const archive={resource_id:'inbox:1:1'};assert.equal(withTransportIdentity(id,'archive_message',archive),archive);
const reply=withReplyParent({...a,parent_resource_id:'inbox:1:1'},{message_id:'<parent@example.test>',references:'<previous@example.test>'});
assert.equal(reply.in_reply_to,'<parent@example.test>');assert.equal(reply.references,'<previous@example.test> <parent@example.test>');
assert.throws(()=>withReplyParent(a,null),/STALE_MAIL_PARENT/);assert.throws(()=>withReplyParent({...a,in_reply_to:'<forged@test>'},{message_id:'<parent@example.test>'}),/SUPPLIED_REPLY_HEADERS_NOT_ALLOWED/);
const replyMime=await canonicalMail('owner@example.test','reply_message',reply);assert(replyMime.bytes.includes(Buffer.from('In-Reply-To: <parent@example.test>')));
const endpoint={host:'127.0.0.1',port:9,tls:'none',auth:{user:'owner@example.test',password:'synthetic-test-only'}};
const provider=createMailProvider({schema_version:'deft.email_account.v1',mode:'loopback_fixture',owner:'owner@example.test',fixture_recipient:'recipient@example.test',smtp:endpoint,imap:endpoint},{allowLoopbackFixture:true});
const approvedReply={...input,parent_resource_id:'inbox:1:1'},derived=withTransportIdentity(id,'reply_message',approvedReply);
const digest=createHash('sha256').update(JSON.stringify({action:'reply_message',input:Object.fromEntries(Object.entries(derived).sort(([a],[b])=>a.localeCompare(b)))})).digest('hex');
const output={operation_id:id,transport_outcome:'smtp_accepted',sent_copy_outcome:'accepted'};
const prior={digest,state:'reported',output};
assert.equal(await provider.effect({latest:()=>prior},id,'reply_message',approvedReply),output,'Replay returns prior receipt before parent lookup or MIME generation');
await assert.rejects(provider.effect({latest:()=>({...prior,digest:'changed'})},id,'reply_message',approvedReply),/RUN_INPUT_CHANGED/);
await assert.rejects(provider.effect({latest:()=>({digest,state:'prepared'})},id,'reply_message',approvedReply),/TRANSPORT_OUTCOME_UNCERTAIN_NO_AUTOMATIC_RESEND/);
console.log(JSON.stringify({passed:true,deterministic_mime:true,trusted_uuid_only:true,supplied_id_denied:true,archive_unchanged:true,effects:0}));
