/**
 * POST /api/agent/followups
 * Body: { userPrompt: string; finalResponse: string }
 * Returns: { followups: string[] }
 *
 * Takes a recently-completed user question and agent response and
 * returns 3 short, topical follow-up suggestions generated by a fast
 * Haiku call. Replaces the hardcoded "Tell me more / What should I
 * focus on next?" fallback in the web client.
 *
 * Cost: ~200 tokens per call at Haiku pricing — sub-$0.0005 each.
 */
import { Hono } from 'hono';
import Anthropic from '@anthropic-ai/sdk';
import { env } from '../lib/env.js';
import { z } from 'zod';

const agentFollowupsRoutes = new Hono();

const BodySchema = z.object({
  userPrompt: z.string().min(1).max(4000),
  finalResponse: z.string().min(1).max(20000),
});

agentFollowupsRoutes.post('/', async (c) => {
  const raw = await c.req.json().catch(() => null);
  const parsed = BodySchema.safeParse(raw);
  if (!parsed.success) {
    return c.json({ error: 'Invalid body', code: 'BAD_REQUEST' }, 400);
  }
  if (!env.ANTHROPIC_API_KEY) {
    return c.json({ followups: [] });
  }

  const client = new Anthropic({ apiKey: env.ANTHROPIC_API_KEY });
  const system =
    'You generate 3 SHORT follow-up question suggestions (5-8 words each) that a user might ask an AI assistant next. Return ONLY a JSON array of 3 strings. No markdown, no preamble.';
  const prompt = `The user asked: "${parsed.data.userPrompt}"

The assistant answered: "${parsed.data.finalResponse.slice(0, 1500)}"

What might the user ask next? Return only a JSON array.`;

  try {
    const response = await client.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 200,
      system,
      messages: [{ role: 'user', content: prompt }],
    });

    const textBlock = response.content.find((b) => b.type === 'text');
    if (!textBlock || textBlock.type !== 'text') {
      return c.json({ followups: [] });
    }

    const match = textBlock.text.match(/\[[\s\S]*\]/);
    if (!match) {
      return c.json({ followups: [] });
    }

    const parsedArray = JSON.parse(match[0]);
    if (!Array.isArray(parsedArray)) {
      return c.json({ followups: [] });
    }

    const followups = parsedArray
      .filter((s): s is string => typeof s === 'string')
      .slice(0, 3)
      .map((s) => s.trim())
      .filter((s) => s.length > 0 && s.length < 100);

    return c.json({ followups });
  } catch (err) {
    console.warn('[agent-followups] failed:', err instanceof Error ? err.message : err);
    return c.json({ followups: [] });
  }
});

export { agentFollowupsRoutes };
