import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test, { after } from 'node:test';
import { and, eq } from 'drizzle-orm';
import { orgs, users, orgMembers, moduleRecords, moduleInstallations, auditLog, projects, tasks } from '@deft/db/schema';
import { db, closeDb } from '../src/lib/db.js';
import { getBundledModule } from '../src/lib/bundled-modules.js';
import { humanModuleActor, installModuleFromManifest, createModuleRecord, archiveModuleRecord, restoreModuleRecord, listArchivedModuleRecords, getModuleRecord, getModuleRecordRelations, listIncomingModuleRecords, updateModuleRecord } from '../src/lib/module-service.js';
import { linkModuleRecordToTask, listModuleRecordTaskLinks } from '../src/lib/module-task-links.js';
import { ModuleError } from '../src/lib/module-errors.js';
import { safeTestDatabaseUrl } from './fixtures/safe-test-database.js';
const url = safeTestDatabaseUrl();
const canRun = Boolean(url);
after(closeDb);

test('archive recovery retains canonical data and live links without resurrecting removed edges', { skip: !canRun }, async () => {
  const orgId = randomUUID(), userId = randomUUID(), projectId = randomUUID(), taskId = randomUUID();
  await db.insert(orgs).values({ id: orgId, name: 'Recovery test', slug: `recovery-${orgId}` });
  await db.insert(users).values({ id: userId, name: 'Recovery owner', email: `${userId}@example.test` });
  await db.insert(orgMembers).values({ id: randomUUID(), org_id: orgId, user_id: userId, role: 'owner', is_active: true });
  const actor = humanModuleActor({ orgId, userId, role: 'owner', source: 'rest' });
  const installation = await installModuleFromManifest(actor, getBundledModule('contacts')!, { source: 'bundled' });
  const create = async (collection: string, data: Record<string, string>, relations: Record<string, string[]> = {}) => (await createModuleRecord(actor, {
    module_id: installation.module_id, collection_key: collection, data, relations, expected_manifest_digest: installation.manifest_digest, idempotency_key: randomUUID(),
  })).record!;
  const company = await create('companies', { name: 'Retained company' });
  const contact = await create('contacts', { name: 'Archived 100% contact', email: 'recover@example.test' }, { company_id: [company.id] });
  const outreach = await create('outreach', { name: 'Original audience', subject: 'Hello' }, { contacts: [contact.id] });
  const activity = await create('activities', { subject: 'Completed call', kind: 'call', outcome: 'completed', occurred_at: '2000-01-01T12:00:00Z' }, { contact_id: [contact.id] });
  await db.insert(projects).values({ id: projectId, org_id: orgId, name: 'Follow-ups', prefix: 'REC' });
  await db.insert(tasks).values({ id: taskId, org_id: orgId, project_id: projectId, number: 1, title: 'Retained next task', created_by: userId, assignee_id: userId, status: 'todo' });
  await linkModuleRecordToTask(actor, taskId, contact.resource_id);
  const archived = await archiveModuleRecord(actor, { record_id: contact.id, expected_revision: contact.revision, expected_manifest_digest: installation.manifest_digest, idempotency_key: randomUUID() });
  await assert.rejects(getModuleRecord(actor, contact.id), /not found/i);
  await updateModuleRecord(actor, { record_id: outreach.id, patch: {}, relations: { contacts: [] }, expected_revision: outreach.revision, expected_manifest_digest: installation.manifest_digest, idempotency_key: randomUUID() });
  const page = await listArchivedModuleRecords(actor, installation.id, { collection_key: 'contacts', search: '100%', limit: 1 });
  assert.equal(page.records.length, 1); assert.equal(page.next_offset, null);
  assert.deepEqual(page.records[0]!.data, contact.data);
  assert.equal((await listArchivedModuleRecords(actor, installation.id, { collection_key: 'companies' })).records.length, 0);
  const second = await create('contacts', { name: 'Second archive', email: 'second@example.test' });
  await archiveModuleRecord(actor, { record_id: second.id, expected_revision: second.revision, expected_manifest_digest: installation.manifest_digest, idempotency_key: randomUUID() });
  const firstPage = await listArchivedModuleRecords(actor, installation.id, { collection_key: 'contacts', limit: 1 });
  assert.equal(firstPage.next_offset, 1);
  const secondPage = await listArchivedModuleRecords(actor, installation.id, { collection_key: 'contacts', limit: 1, offset: firstPage.next_offset });
  assert.equal(secondPage.next_offset, null); assert.notEqual(firstPage.records[0]!.id, secondPage.records[0]!.id);
  const request = { record_id: contact.id, expected_revision: archived.mutation.revision, expected_manifest_digest: installation.manifest_digest, idempotency_key: randomUUID() };
  await assert.rejects(restoreModuleRecord(actor, installation.id, { ...request, expected_revision: contact.revision }), (error: unknown) => error instanceof ModuleError && error.code === 'MODULE_REVISION_CONFLICT');
  const restored = await restoreModuleRecord(actor, installation.id, request);
  assert.equal(restored.mutation.revision, archived.mutation.revision + 1);
  assert.equal((await restoreModuleRecord(actor, installation.id, request)).replayed, true);
  const current = await getModuleRecord(actor, contact.id);
  assert.deepEqual(current.data, contact.data);
  assert.equal(current.id, contact.id);
  assert.equal((await getModuleRecordRelations(actor, contact.id))[0]!.records[0]!.id, company.id);
  assert.equal((await listIncomingModuleRecords(actor, contact.id, { expectedInstallationId: installation.id, collection_key: 'activities', field_key: 'contact_id' })).records[0]!.id, activity.id);
  assert.equal((await getModuleRecordRelations(actor, outreach.id)).find((group) => group.field_key === 'contacts')!.records.length, 0);
  assert.equal((await listModuleRecordTaskLinks(actor, installation.slug, contact.id))[0]!.task_id, taskId);
  assert.equal((await listArchivedModuleRecords(actor, installation.id, { collection_key: 'contacts', search: '100%' })).records.length, 0);
  assert.equal((await db.select().from(auditLog).where(and(eq(auditLog.org_id, orgId), eq(auditLog.action, 'module_record.restore')))).length, 1);
  const guest = humanModuleActor({ orgId, userId, role: 'guest', source: 'rest' });
  await assert.rejects(listArchivedModuleRecords(guest, installation.id, { collection_key: 'contacts' }), /access|denied/i);
  await assert.rejects(restoreModuleRecord(guest, installation.id, request), /access|denied/i);
  const foreignActor = humanModuleActor({ orgId: randomUUID(), userId, role: 'owner', source: 'rest' });
  await assert.rejects(restoreModuleRecord(foreignActor, installation.id, request), /not found|access|denied/i);
  await db.update(moduleInstallations).set({ is_enabled: false, disabled_at: new Date() }).where(eq(moduleInstallations.id, installation.id));
  await assert.rejects(restoreModuleRecord(actor, installation.id, request), /disabled/i);
  await db.update(moduleInstallations).set({ is_enabled: true, disabled_at: null }).where(eq(moduleInstallations.id, installation.id));
  const archivedAgain = await archiveModuleRecord(actor, { record_id: contact.id, expected_revision: current.revision, expected_manifest_digest: installation.manifest_digest, idempotency_key: randomUUID() });
  await db.update(moduleRecords).set({ data: { email: 'recover@example.test' } }).where(eq(moduleRecords.id, contact.id));
  await assert.rejects(restoreModuleRecord(actor, installation.id, { ...request, expected_revision: archivedAgain.mutation.revision, idempotency_key: randomUUID() }), /invalid/i);
  assert.equal((await db.select().from(moduleRecords).where(eq(moduleRecords.id, contact.id)))[0]!.is_deleted, true);
});
